server:
  port: 9001

spring:
  application:
    name: tx
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
  data:
    redis:
      host: localhost
      port: 6379
      database: 1


feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
  hystrix:
    enabled: false
logging:
  config: classpath:logback.xml